$ErrorActionPreference = "Stop"

$appName = "AutoGenerateDaltonArticles"
$templatePdf = (Resolve-Path "template_output.pdf").Path
$duplicationCsv = (Resolve-Path "Duplication_Check_Dalton.csv").Path

Remove-Item -Recurse -Force build, dist -ErrorAction SilentlyContinue

$pyInstallerArgs = @(
    "--noconfirm",
    "--clean",
    "--onefile",
    "--console",
    "--name", $appName,
    "--specpath", "build",
    "--hidden-import", "auto_generate_dalton_articles.scheduler",
    "--hidden-import", "auto_generate_dalton_articles.generate",
    "--hidden-import", "fpdf",
    "--add-data", "$templatePdf;.",
    "--add-data", "$duplicationCsv;.",
    "scheduler_gui.py"
)

python -m PyInstaller @pyInstallerArgs
if ($LASTEXITCODE -ne 0) {
    exit $LASTEXITCODE
}

Write-Host "Built dist\$appName.exe"
